--- #YAML:1.0
name: Lingua-EN-Parse-PersonsName
version: 0.04
author: ~
abstract: A simple parser for english names.
license: perl
requires:
  Class::Accessor::Chained: 0
provides:
  Lingua::EN::Parse::PersonsName:
    file: lib/Lingua/EN/Parse/PersonsName.pm
    version: 0.04
generated_by: Module::Build version 0.2607
